server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
        add_header Content-Type "text/html; charset=utf-8";
    }

    location ~* \.(js|mjs)$ {
        add_header Content-Type "application/javascript; charset=utf-8";
        try_files $uri =404;
    }

    location ~* \.(css)$ {
        add_header Content-Type "text/css; charset=utf-8";
        try_files $uri =404;
    }

    gzip on;
    gzip_types text/plain text/css application/javascript application/json image/svg+xml;
}
